import 'package:hive/hive.dart';

part 'task.g.dart'; // This will be generated by Hive

@HiveType(typeId: 1) // Unique typeId for Hive
class Task {
  @HiveField(0) // Unique fieldId for Hive
  late final String title;

  @HiveField(1)
  bool isCompleted;

  Task({
    required this.title,
    this.isCompleted = false,
  });
}